---

- name: Install common base packages [Debian]
  become: yes
  apt:
    package: "{{ base_packages }}"
    state: latest
    update_cache: yes
    cache_valid_time: 43200
  when:
    - ansible_distribution == 'Debian'

- name: Install common base packages [Debian]
  become: yes
  apt:
    package: "{{ debian_packages }}"
    state: latest
    update_cache: yes
    cache_valid_time: 43200
  when:
    ansible_distribution == 'Debian'

- name: Install common base packages [all]
  become: yes
  package:
    name: "{{ base_packages }}"
    state: latest
  when:
    ansible_distribution != 'Debian'

- name: Install common base packages [Fedora]
  become: yes
  package:
    name: "{{ fedora_packages }}"
    state: latest
  when:
    ansible_distribution == 'Fedora'

- name: Install some common Debian specific packages
  become: yes
  apt:
    package:
      - debian-goodies
      - apt-dater-host
      - apt-transport-https
    state: latest
    update_cache: yes
    cache_valid_time: 43200
  when: ansible_distribution == 'Debian'


- name: Remove rpcbind, nfs-common
  become: yes
  package:
    name:
      - rpcbind
      - nfs-common
    state: absent


