---
- include_tasks: os_info.yml
  when: print_os_vars | bool

- include_tasks: versioncheck.yml
  when: submodules_versioncheck | bool

- include_tasks: sources.yml
  when:
    - ansible_os_family == 'Debian'
    - base__add_ethz | bool
    - ansible_architecture == 'x86_64'

- include_tasks: packages.yml

- name: Upgrade all packages to latest
  become: true
  package:
    name: "*"
    state: "{{ base__package_state }}"
  when:
    - base__upgrade_packages_to_latest_version|bool

- include_tasks: editor.yml
  when: editor_is_vim | bool
