---
- include_tasks: versioncheck.yml
  when: submodules_versioncheck | bool

- include_tasks: editor.yml
  when: editor_is_vim | bool

- name: Install common base packages [Debian]
  become: yes
  apt:
    package: "{{ debian_packages }}"
    state: present
    update_cache: yes
    cache_valid_time: 43200
  when:
    ansible_os_family == 'Debian'

- name: Install common base packages [all]
  become: yes
  package:
    name: "{{ base_packages }}"
    state: present

- name: Install common base packages [Fedora]
  become: yes
  package:
    name: "{{ fedora_packages }}"
    state: present
  when:
    ansible_distribution == 'Fedora'

- name: Install some common Debian specific packages
  become: yes
  apt:
    package:
      - debian-goodies
      - apt-dater-host
      - apt-transport-https
    state: present
    update_cache: yes
    cache_valid_time: 43200
  when: ansible_distribution == 'Debian'

- name: install packages for everyone except centos/rhel
  become: true
  package:
    name: "{{ packages_for_all_except_rhel }}"
    state: present
  when: ansible_os_family != 'RedHat'

- name: Install extra packages
  become: true
  package:
    name: "{{ packages_extra }}"
    state: present
  when:
    - packages_extra is defined
    - packages_extra != '[]'

- name: Remove rpcbind, nfs-common
  become: yes
  package:
    name:
      - rpcbind
      - nfs-common
    state: absent

- name: Upgrade all packages to latest
  become: true
  package:
    name: "*"
    state: latest
  when:
    - upgrade_packages_to_latest_version|bool
