---

- name: Install some common base packages
  apt:
    state: 'latest'
    name: "{{ packages }}"
    update_cache: yes
    cache_valid_time: 86400
  vars:
    packages:
    - tmux
    - aptitude
    - htop
    - iftop
    - iotop
    - molly-guard
    - ethtool
    - ethstatus
    - nano
    - ncdu
    - haveged
    - nmap
    - vim
    - fail2ban
    - python3
    - python3-jsonschema
    - python3-yaml
    - python3-requests
    - python3-prettytable
    - python3-jinja2
    - python3-natsort
    - jq
    - git
    - perl
    - wget
    - mtr-tiny
    - bash-completion
    - unzip
    - python3-pip 

- name: Install some common Debian specific packages
  apt:
    name: '{{ packages }}'
    state: latest
    update_cache: yes
    cache_valid_time: 86400
  vars:
    packages:
    - debian-goodies
    - apt-dater-host
  when: ansible_distribution == 'Debian'

- name: Update all packages to the latest version
  apt:
    upgrade: safe
