---
- include_tasks: os_info.yml
  when: print_os_vars | bool

- include_tasks: versioncheck.yml
  when: submodules_versioncheck | bool

- include_tasks: sources.yml
  when:
    - base__add_ethz | bool
    - ansible_architecture == 'x86_64'
    - ansible_distribution == 'Debian' and ansible_distribution_version | float >= 8

- include_tasks: packages.yml

- name: Upgrade all packages to latest
  become: true
  package:
    name: "*"
    state: "{{ base__package_state }}"
  when:
    - base__upgrade_packages_to_latest_version|bool

- include_tasks: editor.yml
  when: base__install_vim | bool

- include_tasks: keychain.yml
  when: base__install_keychain | bool
