---
---
- name: Install common base packages
  apt:
    package:
      - tmux
      - sudo
      - molly-guard
      - htop
      - iftop
      - iotop
      - sysstat
      - ethtool
      - ethstatus
      - nethogs
      - nload
      - ncdu
      - mtr-tiny
      - knot-dnsutils
      - atop
      - vim
      - nmap
      - python3
      - wget
      - git
      - bash-completion
      - unzip
      - python3-pip 
      #- rng-tools
    state: latest
    update_cache: yes
    cache_valid_time: 43200

- name: Install some common Debian specific packages
  apt:
    package:
      - debian-goodies
      - apt-dater-host
    state: latest
    update_cache: yes
    cache_valid_time: 43200
  when: ansible_distribution == 'Debian'


- name: Remove rpcbind, nfs-common
  apt:
    pkg:
      - rpcbind
      - nfs-common
    state: absent


